# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

approximate <- function(t_obs, matData, knotIndex, knotDiff, continuous, r) {
    .Call('operatorCalc_approximate', PACKAGE = 'operatorCalc', t_obs, matData, knotIndex, knotDiff, continuous, r)
}

backward <- function(diffs, f, g) {
    .Call('operatorCalc_backward', PACKAGE = 'operatorCalc', diffs, f, g)
}

evaluate <- function(jj, s, f, g) {
    .Call('operatorCalc_evaluate', PACKAGE = 'operatorCalc', jj, s, f, g)
}

forward <- function(diffs, f, g) {
    .Call('operatorCalc_forward', PACKAGE = 'operatorCalc', diffs, f, g)
}

integral <- function(diffs, f, g) {
    .Call('operatorCalc_integral', PACKAGE = 'operatorCalc', diffs, f, g)
}

inv_beta <- function(alpha_f, alpha_g, beta_f, beta_g, lambda, order, super, continuous) {
    .Call('operatorCalc_inv_beta', PACKAGE = 'operatorCalc', alpha_f, alpha_g, beta_f, beta_g, lambda, order, super, continuous)
}

inv_gamma <- function(alpha_f, alpha_g, gamma_f, gamma_g, lambda, order, super, continuous) {
    .Call('operatorCalc_inv_gamma', PACKAGE = 'operatorCalc', alpha_f, alpha_g, gamma_f, gamma_g, lambda, order, super, continuous)
}

inverse <- function(f, g, order, super, continuous) {
    .Call('operatorCalc_inverse', PACKAGE = 'operatorCalc', f, g, order, super, continuous)
}

multFct <- function(f1, g1, f2, g2) {
    .Call('operatorCalc_multFct', PACKAGE = 'operatorCalc', f1, g1, f2, g2)
}

multFct_left <- function(x, f, g) {
    .Call('operatorCalc_multFct_left', PACKAGE = 'operatorCalc', x, f, g)
}

multFct_right <- function(f, g, y) {
    .Call('operatorCalc_multFct_right', PACKAGE = 'operatorCalc', f, g, y)
}

solveFct <- function(f1, g1, f2, g2, order, super, continuous) {
    .Call('operatorCalc_solveFct', PACKAGE = 'operatorCalc', f1, g1, f2, g2, order, super, continuous)
}

superSample <- function(choose, jj, a, b, f, g) {
    .Call('operatorCalc_superSample', PACKAGE = 'operatorCalc', choose, jj, a, b, f, g)
}

triangular <- function(diffs, f, g) {
    .Call('operatorCalc_triangular', PACKAGE = 'operatorCalc', diffs, f, g)
}

